version: "3.7"

services:
  polygon_minter:
    build:
      context: jobs/polygon_minter
      dockerfile: local.dockerfile
    entrypoint: npm
    command: [ run, dev:watch ]
    working_dir: /home/app/jobs/polygon_minter
    volumes:
      - .:/home/app

  polygon_claimable_processor:
    build:
      context: jobs/polygon_claimable_processor
      dockerfile: local.dockerfile
    entrypoint: npm
    command: [ run, dev:watch ]
    working_dir: /home/app/jobs/polygon_claimable_processor
    volumes:
      - .:/home/app

  polygon_callback:
    build:
      context: jobs/polygon_minter
      dockerfile: local.dockerfile
    entrypoint: npm
    command: [ run, callback-server ]
    working_dir: /home/app/jobs/polygon_minter
    volumes:
      - .:/home/app

  claimables-front:
    build:
      context: frontend/claimables
      dockerfile: local.dockerfile
    entrypoint: yarn
    command: [ run, dev ]
    working_dir: /home/app/frontend/claimables
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
