version: "3.7"

services:
  polygon_minter:
    build:
      context: jobs/polygon_minter
      dockerfile: local.dockerfile
    entrypoint: npm
    command: [ run, dev:watch ]
    working_dir: /home/app/jobs/polygon_minter
    volumes:
      - .:/home/app

  polygon_callback:
    build:
      context: jobs/polygon_minter
      dockerfile: local.dockerfile
    entrypoint: npm
    command: [ run, callback-server ]
    working_dir: /home/app/jobs/polygon_minter
    volumes:
      - .:/home/app
