version: "3.7"

services:
  polygon_minter:
    build:
      context: .
      dockerfile: jobs/polygon_minter/dockerfile
    env_file:
      - polygon_minter.env
    restart: unless-stopped
  
  polygon_claimable_processor:
    build:
      context: .
      dockerfile: jobs/polygon_claimable_processor/dockerfile
    env_file:
      - polygon_claimable_processor.env
    restart: unless-stopped