/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  EIP2771ContextUpgradeable,
  EIP2771ContextUpgradeableInterface,
} from "../../contracts/EIP2771ContextUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class EIP2771ContextUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): EIP2771ContextUpgradeableInterface {
    return new utils.Interface(_abi) as EIP2771ContextUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EIP2771ContextUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as EIP2771ContextUpgradeable;
  }
}
