
const POLYGON_NETWORK_ID = process.env.NEXT_PUBLIC_POLYGON_NETWORK_ID as string;

const POLYGON_CLAIM_TOKEN_ADDRESS = process.env.NEXT_PUBLIC_POLYGON_CLAIM_TOKEN_ADDRESS as string;

const POLYGON_TRUSTED_FORWARDER_ADDRESS = process.env.NEXT_PUBLIC_POLYGON_TRUSTED_FORWARDER_ADDRESS as string;

const POLYGON_OPENSEA_BASE_URL = process.env.NEXT_PUBLIC_POLYGON_OPENSEA_BASE_URL as string;

const POLYGON_BICONOMY_API_KEY = process.env.NEXT_PUBLIC_POLYGON_BICONOMY_API_KEY as string;

const POLYGON_BICONOMY_API_ID = process.env.NEXT_PUBLIC_POLYGON_BICONOMY_API_ID as string;

const NEAR_NETWORK_NAME = process.env.NEXT_PUBLIC_NEAR_NETWORK_NAME ?? "testnet";

const NEAR_VAULT_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_NEAR_VAULT_CONTRACT_ADDRESS ?? "vault.world-triathlon.testnet";

const NEAR_ACCOUNT_POSTFIX = NEAR_NETWORK_NAME === 'mainnet' ? '.near' : '.testnet';

const ACTIVITY_REPORT_URL = process.env.NEXT_PUBLIC_ACTIVITY_REPORT_URL ?? 'https://testminter.azurewebsites.net/claim-activity';

export {
    POLYGON_NETWORK_ID,
    POLYGON_CLAIM_TOKEN_ADDRESS,
    POLYGON_TRUSTED_FORWARDER_ADDRESS,
    POLYGON_OPENSEA_BASE_URL,
    POLYGON_BICONOMY_API_KEY,
    POLYGON_BICONOMY_API_ID,
    NEAR_NETWORK_NAME,
    NEAR_VAULT_CONTRACT_ADDRESS,
    NEAR_ACCOUNT_POSTFIX,
    ACTIVITY_REPORT_URL
}