

const CLAIM_TOKEN_ADDRESS = process.env.NEXT_PUBLIC_CLAIM_TOKEN_ADDRESS as string;

const TRUSTED_FORWARDER_ADDRESS = process.env.NEXT_PUBLIC_TRUSTED_FORWARDER_ADDRESS as string;

const OPENSEA_BASE_URL = process.env.NEXT_PUBLIC_OPENSEA_BASE_URL as string;

const BICONOMY_API_KEY = process.env.NEXT_PUBLIC_BICONOMY_API_KEY as string;

const BICONOMY_API_ID = process.env.NEXT_PUBLIC_BICONOMY_API_ID as string;

export {
    CLAIM_TOKEN_ADDRESS,
    TRUSTED_FORWARDER_ADDRESS,
    OPENSEA_BASE_URL,
    BICONOMY_API_KEY,
    BICONOMY_API_ID
}