FROM node:16.6.2 as build

WORKDIR /workdir
COPY . /workdir

RUN apt-get update && apt-get -y install git
RUN yarn install && yarn build

FROM node:16.6.2-alpine3.14 as runtime

WORKDIR /home/polygon_minter

COPY --from=build /workdir/dist /home/polygon_minter/dist
COPY --from=build /workdir/package.json /home/polygon_minter/package.json
COPY --from=build /workdir/yarn.lock /home/polygon_minter/yarn.lock

RUN apk update && apk add git

ENV NODE_ENV production

RUN yarn install && \
    chown -R node:node /home/polygon_minter && \
    find /home/polygon_minter -type f -exec chmod 400 {} \; && \
    find /home/polygon_minter -type d -exec chmod 500 {} \;

LABEL Maintainer="Marc Par <marc.par10@gmail.com>"
LABEL Repository="https://github.com/marcpar/polygon_processor"
USER node

ENTRYPOINT ["sh", "-c"]
CMD ["node dist/index.js"]
